### ISSUE TITLE
Error: Cannot find module 'moment'

### ISSUE THREAD

**Issue by glezster** [standardize-network/querynode#1]
module.js:549
    throw err;
    ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/querynode/app.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by consuman** [comment]
Hi! Have you run `npm install` to install moment?

Edit: It is listed in the package.json file and should be added afterwords in a new folder `node_modules`. It will be triggered, when you run `npm install`, while you are in the `querynode` folder. :)
